name: Package Application for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: zcb
        path: src/dist/windows
  
  pre-release:
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch latest build artifact
        uses: actions/download-artifact@v1
        with:
          name: zcb
          path: ./zcb
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Create Release and Upload Assets
        id: create_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Windows Development Build"
          files: |
            zcb/zcb.exe
            checksums.txt
       
